package com.jadroid.launcher.launch

import com.jadroid.launcher.BuildConfig
import com.jadroid.launcher.core.AppLog
import com.jadroid.launcher.core.LauncherPaths
import com.jadroid.launcher.core.shellQuote
import com.jadroid.launcher.data.auth.Account
import com.jadroid.launcher.data.instance.Instance
import com.jadroid.launcher.data.minecraft.ResolvedVersion
import com.jadroid.launcher.data.mojang.LaunchFeatures
import com.jadroid.launcher.data.mojang.OsProfile
import com.jadroid.launcher.data.mojang.RuleEvaluator
import com.jadroid.launcher.data.settings.AppSettings
import java.io.File

/** A fully resolved java invocation, ready to be handed to the game process runner. */
data class LaunchCommand(
    val javaExecutable: File,
    val workingDir: File,
    val jvmArgs: List<String>,
    val mainClass: String,
    val gameArgs: List<String>,
    val classpath: List<File>,
    val environment: Map<String, String>
) {
    fun toArgumentList(): List<String> = buildList {
        add(javaExecutable.absolutePath)
        addAll(jvmArgs)
        add(mainClass)
        addAll(gameArgs)
    }

    fun toDisplayString(): String = toArgumentList().joinToString(" ") { quote(it) }

    /** Exported for advanced users / external runtimes such as Termux. */
    fun toScript(): String = buildString {
        appendLine("#!/system/bin/sh")
        appendLine("# Launch script generated by Jadroid")
        environment.forEach { (key, value) -> appendLine("export $key=${value.shellQuote()}") }
        appendLine("cd ${workingDir.absolutePath.shellQuote()} || exit 1")
        appendLine("exec ${toDisplayString()}")
    }

    private fun quote(value: String): String =
        if (value.any { it == ' ' || it == '"' || it == '\'' || it == '(' }) "\"$value\"" else value
}

/**
 * Builds the java command line exactly like the official launcher does: placeholder substitution
 * over the version json `arguments` (or the legacy `minecraftArguments` string for old versions).
 */
class LaunchCommandBuilder(private val paths: LauncherPaths) {

    fun build(
        instance: Instance,
        account: Account,
        resolved: ResolvedVersion,
        classpath: List<File>,
        nativesDirectory: File,
        javaExecutable: File,
        os: OsProfile,
        features: LaunchFeatures,
        settings: AppSettings,
        launcherName: String = "Jadroid",
        launcherVersion: String = BuildConfig.VERSION_NAME
    ): LaunchCommand {
        val json = resolved.json
        val gameDir = paths.gameDir(instance.id)
        val featureMap = features.toMap()
        val classpathString = classpath.joinToString(File.pathSeparator) { it.absolutePath }
        val assetsIndexName = json.assetIndex?.id ?: json.assets ?: "legacy"
        val accessToken = account.accessToken ?: "0"

        val substitutions = mapOf(
            "auth_player_name" to account.username,
            "auth_uuid" to account.compactUuid,
            "auth_access_token" to accessToken,
            "auth_session" to "token:$accessToken:${account.compactUuid}",
            "auth_xuid" to (account.xuid ?: "0"),
            "clientid" to settings.msClientId,
            "user_type" to if (account.isMicrosoft) "msa" else "legacy",
            "user_properties" to "{}",
            "version_name" to resolved.id,
            "version_type" to (json.type ?: "release"),
            "game_directory" to gameDir.absolutePath,
            "game_assets" to File(paths.assets, "virtual/${json.assets ?: "legacy"}").absolutePath,
            "assets_root" to paths.assets.absolutePath,
            "assets_index_name" to assetsIndexName,
            "natives_directory" to nativesDirectory.absolutePath,
            "classpath" to classpathString,
            "classpath_separator" to File.pathSeparator,
            "library_directory" to paths.libraries.absolutePath,
            "launcher_name" to launcherName,
            "launcher_version" to launcherVersion,
            "resolution_width" to instance.resolutionWidth.toString(),
            "resolution_height" to instance.resolutionHeight.toString(),
            "quickPlayPath" to "",
            "quickPlaySingleplayer" to "",
            "quickPlayMultiplayer" to "",
            "quickPlayRealms" to ""
        )

        val jsonJvmArgs = json.arguments?.jvm.orEmpty()
            .filter { RuleEvaluator.isAllowed(it.rules, os, featureMap) }
            .flatMap { it.values }
        val jvmArgs = buildList {
            add("-Xmx${instance.allocatedRamMb.coerceAtLeast(512)}m")
            add("-Xms${(instance.allocatedRamMb / 2).coerceAtLeast(256)}m")
            if (jsonJvmArgs.isNotEmpty()) {
                addAll(jsonJvmArgs)
                if (jsonJvmArgs.none { it.contains("java.library.path") }) {
                    add("-Djava.library.path=${nativesDirectory.absolutePath}")
                }
            } else {
                add("-Djava.library.path=${nativesDirectory.absolutePath}")
            }
            if (jsonJvmArgs.none { it == "-cp" || it == "-classpath" }) {
                add("-cp")
                add(classpathString)
            }
        }.map { substitute(it, substitutions) }

        val userJvmArgs = splitArguments(instance.jvmArgs.ifBlank { settings.defaultJvmArgs })
            .map { substitute(it, substitutions) }

        return finish(
            instance = instance,
            resolved = resolved,
            account = account,
            javaExecutable = javaExecutable,
            gameDir = gameDir,
            nativesDirectory = nativesDirectory,
            classpath = classpath,
            jvmArgs = jvmArgs + userJvmArgs,
            featureMap = featureMap,
            os = os,
            substitutions = substitutions
        )
    }

    private fun finish(
        instance: Instance,
        resolved: ResolvedVersion,
        account: Account,
        javaExecutable: File,
        gameDir: File,
        nativesDirectory: File,
        classpath: List<File>,
        jvmArgs: List<String>,
        os: OsProfile,
        featureMap: Map<String, Boolean>,
        substitutions: Map<String, String>
    ): LaunchCommand {
        val json = resolved.json
        val jsonGameArgs = json.arguments?.game.orEmpty()
            .filter { RuleEvaluator.isAllowed(it.rules, os, featureMap) }
            .flatMap { it.values }
        val gameArgs = when {
            jsonGameArgs.isNotEmpty() -> jsonGameArgs
            !json.legacyMinecraftArguments.isNullOrBlank() ->
                json.legacyMinecraftArguments!!.split(' ').filter { it.isNotBlank() }
            else -> emptyList()
        }.map { substitute(it, substitutions) }

        val javaHome = javaExecutable.parentFile?.parentFile
        val environment = buildMap {
            put("HOME", gameDir.absolutePath)
            put("LD_LIBRARY_PATH", nativesDirectory.absolutePath)
            javaHome?.let { put("JAVA_HOME", it.absolutePath) }
        }

        AppLog.i(
            "Launching ${instance.name} as ${account.username} " +
                "(${if (account.isMicrosoft) "Microsoft" else "local"} account, ${jvmArgs.size} jvm args)"
        )

        return LaunchCommand(
            javaExecutable = javaExecutable,
            workingDir = gameDir,
            jvmArgs = jvmArgs,
            mainClass = json.mainClass ?: "net.minecraft.client.main.Main",
            gameArgs = gameArgs,
            classpath = classpath,
            environment = environment
        )
    }

    private fun substitute(value: String, substitutions: Map<String, String>): String {
        var result = value
        substitutions.forEach { (key, replacement) ->
            result = result.replace("\${$key}", replacement)
        }
        return result
    }

    /** Splits a user provided argument string while honouring simple quoting. */
    private fun splitArguments(raw: String): List<String> {
        if (raw.isBlank()) return emptyList()
        val result = mutableListOf<String>()
        val current = StringBuilder()
        var quote: Char? = null
        raw.forEach { char ->
            when {
                quote != null && char == quote -> quote = null
                quote != null -> current.append(char)
                char == '"' || char == '\'' -> quote = char
                char.isWhitespace() -> {
                    if (current.isNotEmpty()) {
                        result += current.toString()
                        current.clear()
                    }
                }
                else -> current.append(char)
            }
        }
        if (current.isNotEmpty()) result += current.toString()
        return result
    }
}
